### PR TITLE
Implement the ability to have fixed y axis

### LINKED ISSUE #32: Fixed y-axis plotting for live plotting
Having a fixed y axis can be nice, especially for live plotting:

https://user-images.githubusercontent.com/12289754/129968255-6c2fce68-6291-4d66-9ac3-ab2b865bcacc.mov

### PR DESCRIPTION
**Pull request by TDHolmes**
Closes #32 

https://user-images.githubusercontent.com/12289754/130336549-f7d8e10b-fc48-4208-93ba-2d7dc70b8111.mov

### CODE REVIEW

**Comment by TDHolmes** [comment]
Oh I didn't think of this at the time, but if you want I can update the CLI version to have optional y range. Sounds like #30 would benefit from it ([this comment](https://github.com/loony-bean/textplots-rs/issues/30#issuecomment-877852906))

**Comment by loony-bean** [comment]
Yeah, I guess CLI should be updated as well. Also, any chance of adding your demo as example? It's so cool

**Comment by TDHolmes** [comment]
done!

**Comment by TDHolmes** [comment]
Also I'm open to naming suggestions for the new `new` method, if anyone has a better idea

**Comment by loony-bean** [comment]
I'm happy to merge this. I just wanted to merges this after https://github.com/loony-bean/textplots-rs/pull/34

Naming is not a big concern for me because we are in 0.x, and also I believe that at some point we will need to add ability to have fixed x axis as well. Maybe we'll refactor things a bit then.

**Comment by loony-bean** [comment]
Nice work @TDHolmes! Thanks 😍

**Comment by ahcm** [comment]
Thanks!

**Pull request merged**
