### PR TITLE
switch to GitHub Actions

### PR DESCRIPTION
**Pull request by TDHolmes**
No worries if you want to stick with Travis for CI, but thought I'd throw it up to see what you thought. Since it's coming from a fork you won't see the CI running, but see [this PR on my fork](https://github.com/TDHolmes/textplots-rs/pull/1) for what it'd look like for future PRs if you merged.

### CODE REVIEW

**Comment by TDHolmes** [comment]
- [ ] Delete Travis yaml

**Comment by loony-bean** [comment]
This looks amazing! I'd love to switch to GA.
One question though - do you use nightly toolchain to run checks?

**Comment by TDHolmes** [comment]
It currently uses nightly, but can be switched. See [this line](https://github.com/loony-bean/textplots-rs/pull/34/files#diff-73e17259d77e5fbef83b2bdbbe4dc40a912f807472287f7f45b77e0cbf78792dR23)

**Comment by loony-bean** [comment]
Got it. Could we switch to `stable` please? since we are not using any `nightly` features.

Another thing I wanted to ask, if you could run all the examples in the CI. IMHO it will be a nice addition to tests, to make sure examples do no produce runtime errors.

**Comment by TDHolmes** [comment]
sure, but I'll have to change my live plot example to only run for a
limited time. Maybe like ~5s?

**Comment by loony-bean** [comment]
5s is fine 👍

**Comment by TDHolmes** [comment]
[This is working](https://github.com/TDHolmes/textplots-rs/actions/runs/1177728353) and good to merge!

**Comment by loony-bean** [comment]
Thanks @TDHolmes!

**Pull request merged**
